global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: "app_metrics"
    metrics_path: /metrics
    static_configs:
      - targets: ["url-sas:8080"]
