# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # 1. Install dependencies at the project root
      - name: Install dependencies
        run: npm install

      # 2. Run all Jest tests (app.test.js, plus any others)
      - name: Run tests
        run: npm test

      # 3. Deploy only if the tests passed
      - name: Deploy to EC2
        if: success()
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            set -e
            # Make sure the target folder exists on EC2
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/temp_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "mkdir -p ${{ secrets.APP_PATH }}"

            # Rsync everything from the repo root to EC2:/path/to/app
            rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/temp_key.pem" ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.APP_PATH }}/

            # On EC2, install production dependencies & restart the service
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/temp_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
              cd ${{ secrets.APP_PATH }}
              npm install --production
              sudo systemctl restart node-app.service
            EOF
