name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # 3) Install dependencies (inside the app/ folder)
      - name: Install dependencies
        working-directory: app
        run: npm install

      # 4) Run tests (inside the app/ folder)
      - name: Run tests
        working-directory: app
        run: npm test

      # 5) Deploy to EC2 if tests passed
      - name: Deploy to EC2
        if: success()
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          # (Optional) disable strict host key checking if you see unknown-host warnings:
          ssh_args: -o StrictHostKeyChecking=no
          script: |
            set -e

            # Ensure the remote app folder exists
            mkdir -p ${{ secrets.APP_PATH }}

            # Sync the entire app directory to EC2
            rsync -avz ./app/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.APP_PATH }}/

            # On EC2: cd into the app folder, install prod deps, restart service
            cd ${{ secrets.APP_PATH }}
            npm install --production
            sudo systemctl restart node-app.service
